// Auto-generated by protoc-gen-ladybug — do not edit.

export const NODE_SCHEMA_STATEMENTS = [
  `CREATE NODE TABLE IF NOT EXISTS File(id STRING PRIMARY KEY, name STRING, path STRING, language STRING, lines INT32, checksum BLOB, labels STRING[])`,
  `CREATE NODE TABLE IF NOT EXISTS Function(id STRING, name STRING PRIMARY KEY, signature STRING, startLine INT32, endLine INT32, exported BOOL, complexity INT32)`,
  `CREATE NODE TABLE IF NOT EXISTS Class(id STRING PRIMARY KEY, name STRING, kind STRING, start_line INT32, end_line INT32, exported BOOL, implements STRING[])`,
  `CREATE NODE TABLE IF NOT EXISTS Package(id STRING, name STRING, version STRING, path STRING PRIMARY KEY)`,
  `CREATE NODE TABLE IF NOT EXISTS Service(id STRING PRIMARY KEY, name STRING, repoUrl STRING, port UINT32, owners STRING[])`,
] as const;

export const NODE_TYPES = [
  'File',
  'Function',
  'Class',
  'Package',
  'Service',
] as const;

export type NodeType = (typeof NODE_TYPES)[number];

export const REL_SCHEMA = {
  CALLS: (from: string, to: string) =>
    `CREATE REL TABLE IF NOT EXISTS CALLS(FROM ${from} TO ${to}, id STRING, args STRING, confidence FLOAT)`,
  DEFINED_IN: (from: string, to: string) =>
    `CREATE REL TABLE IF NOT EXISTS DEFINED_IN(FROM ${from} TO ${to}, id STRING, startLine INT32, endLine INT32)`,
  DEPENDS_ON: (from: string, to: string) =>
    `CREATE REL TABLE IF NOT EXISTS DEPENDS_ON(FROM ${from} TO ${to}, id STRING, version STRING, dev BOOL)`,
} as const;

export const REL_TYPES = [
  'CALLS',
  'DEFINED_IN',
  'DEPENDS_ON',
] as const;

export type RelType = (typeof REL_TYPES)[number];
