# Auto-generated by protoc-gen-ladybug — do not edit.

from typing import Final, Literal

NODE_SCHEMA_STATEMENTS: Final[list[str]] = [
    "CREATE NODE TABLE IF NOT EXISTS File(id STRING PRIMARY KEY, name STRING, path STRING, language STRING, lines INT32, checksum BLOB, labels STRING[])",
    "CREATE NODE TABLE IF NOT EXISTS Function(id STRING, name STRING PRIMARY KEY, signature STRING, startLine INT32, endLine INT32, exported BOOL, complexity INT32)",
    "CREATE NODE TABLE IF NOT EXISTS Class(id STRING PRIMARY KEY, name STRING, kind STRING, start_line INT32, end_line INT32, exported BOOL, implements STRING[])",
    "CREATE NODE TABLE IF NOT EXISTS Package(id STRING, name STRING, version STRING, path STRING PRIMARY KEY)",
    "CREATE NODE TABLE IF NOT EXISTS Service(id STRING PRIMARY KEY, name STRING, repoUrl STRING, port UINT32, owners STRING[])",
]

NODE_TYPE_FILE: Final[str] = "File"
NODE_TYPE_FUNCTION: Final[str] = "Function"
NODE_TYPE_CLASS: Final[str] = "Class"
NODE_TYPE_PACKAGE: Final[str] = "Package"
NODE_TYPE_SERVICE: Final[str] = "Service"

NodeType = Literal["File"] | Literal["Function"] | Literal["Class"] | Literal["Package"] | Literal["Service"]

NODE_TYPES: Final[list[NodeType]] = [
    NODE_TYPE_FILE,
    NODE_TYPE_FUNCTION,
    NODE_TYPE_CLASS,
    NODE_TYPE_PACKAGE,
    NODE_TYPE_SERVICE,
]

NODE_COLUMNS: Final[dict[NodeType, list[tuple[str, str]]]] = {
    "File": [
        ("id", "STRING"),
        ("name", "STRING"),
        ("path", "STRING"),
        ("language", "STRING"),
        ("lines", "INT32"),
        ("checksum", "BLOB"),
        ("labels", "STRING[]"),
    ],
    "Function": [
        ("id", "STRING"),
        ("name", "STRING"),
        ("signature", "STRING"),
        ("startLine", "INT32"),
        ("endLine", "INT32"),
        ("exported", "BOOL"),
        ("complexity", "INT32"),
    ],
    "Class": [
        ("id", "STRING"),
        ("name", "STRING"),
        ("kind", "STRING"),
        ("start_line", "INT32"),
        ("end_line", "INT32"),
        ("exported", "BOOL"),
        ("implements", "STRING[]"),
    ],
    "Package": [
        ("id", "STRING"),
        ("name", "STRING"),
        ("version", "STRING"),
        ("path", "STRING"),
    ],
    "Service": [
        ("id", "STRING"),
        ("name", "STRING"),
        ("repoUrl", "STRING"),
        ("port", "UINT32"),
        ("owners", "STRING[]"),
    ],
}

NODE_COLUMN_NAMES: Final[dict[NodeType, list[str]]] = {
    "File": [
        "id",
        "name",
        "path",
        "language",
        "lines",
        "checksum",
        "labels",
    ],
    "Function": [
        "id",
        "name",
        "signature",
        "startLine",
        "endLine",
        "exported",
        "complexity",
    ],
    "Class": [
        "id",
        "name",
        "kind",
        "start_line",
        "end_line",
        "exported",
        "implements",
    ],
    "Package": [
        "id",
        "name",
        "version",
        "path",
    ],
    "Service": [
        "id",
        "name",
        "repoUrl",
        "port",
        "owners",
    ],
}


# A (from_node, to_node) pair for a relationship table.
#
# Ladybug requires every pair a rel label spans to be declared in the
# initial CREATE REL TABLE statement; subsequent CREATE REL TABLE IF
# NOT EXISTS calls for the same label are silent no-ops. Pass every
# pair the label needs in a single rel_schema_* call.
RelPair = tuple[str, str]


def _join_rel_pairs(pairs: list[RelPair]) -> str:
    return ", ".join(f"FROM {p[0]} TO {p[1]}" for p in pairs)


def rel_schema_calls(pairs: list[RelPair]) -> str:
    """Return the CREATE REL TABLE DDL for Calls relationships.

    Pass every (from, to) pair the CALLS label needs in a single call;
    all pairs must be declared in the initial CREATE REL TABLE statement.
    """
    return f"CREATE REL TABLE IF NOT EXISTS CALLS({_join_rel_pairs(pairs)}, id STRING, args STRING, confidence FLOAT)"


def rel_schema_defined_in(pairs: list[RelPair]) -> str:
    """Return the CREATE REL TABLE DDL for DefinedIn relationships.

    Pass every (from, to) pair the DEFINED_IN label needs in a single call;
    all pairs must be declared in the initial CREATE REL TABLE statement.
    """
    return f"CREATE REL TABLE IF NOT EXISTS DEFINED_IN({_join_rel_pairs(pairs)}, id STRING, startLine INT32, endLine INT32)"


def rel_schema_depends_on(pairs: list[RelPair]) -> str:
    """Return the CREATE REL TABLE DDL for DependsOn relationships.

    Pass every (from, to) pair the DEPENDS_ON label needs in a single call;
    all pairs must be declared in the initial CREATE REL TABLE statement.
    """
    return f"CREATE REL TABLE IF NOT EXISTS DEPENDS_ON({_join_rel_pairs(pairs)}, id STRING, version STRING, dev BOOL)"


REL_TYPE_CALLS: Final[str] = "CALLS"
REL_TYPE_DEFINED_IN: Final[str] = "DEFINED_IN"
REL_TYPE_DEPENDS_ON: Final[str] = "DEPENDS_ON"

RelType = Literal["CALLS"] | Literal["DEFINED_IN"] | Literal["DEPENDS_ON"]

REL_TYPES: Final[list[RelType]] = [
    REL_TYPE_CALLS,
    REL_TYPE_DEFINED_IN,
    REL_TYPE_DEPENDS_ON,
]

REL_COLUMNS: Final[dict[RelType, list[tuple[str, str]]]] = {
    "CALLS": [
        ("id", "STRING"),
        ("args", "STRING"),
        ("confidence", "FLOAT"),
    ],
    "DEFINED_IN": [
        ("id", "STRING"),
        ("startLine", "INT32"),
        ("endLine", "INT32"),
    ],
    "DEPENDS_ON": [
        ("id", "STRING"),
        ("version", "STRING"),
        ("dev", "BOOL"),
    ],
}

REL_COLUMN_NAMES: Final[dict[RelType, list[str]]] = {
    "CALLS": [
        "id",
        "args",
        "confidence",
    ],
    "DEFINED_IN": [
        "id",
        "startLine",
        "endLine",
    ],
    "DEPENDS_ON": [
        "id",
        "version",
        "dev",
    ],
}


_COLUMN_TO_PROTO: Final[dict[NodeType | RelType, dict[str, str]]] = {
    "Function": {"startLine": "start_line", "endLine": "end_line"},
    "Service": {"repoUrl": "repo_url"},
    "DEFINED_IN": {"startLine": "start_line", "endLine": "end_line"},
}

_PROTO_TO_COLUMN: Final[dict[NodeType | RelType, dict[str, str]]] = {
    "Function": {"start_line": "startLine", "end_line": "endLine"},
    "Service": {"repo_url": "repoUrl"},
    "DEFINED_IN": {"start_line": "startLine", "end_line": "endLine"},
}


def ladybug_to_proto(type_name: NodeType | RelType, row: dict[str, object]) -> dict[str, object]:
    """Remap LadybugDB column names to protobuf field names.

    Use this when reading a row from the database and converting it to a
    protobuf message via ``ParseDict``. Only columns with a ``(ladybug.column)``
    override are remapped; all other keys pass through unchanged. Returns the
    input unchanged for types with no remapped columns.

    Example::

        row = {"id": "s1", "name": "api", "repoUrl": "https://..."}
        msg = ParseDict(ladybug_to_proto("Service", row), ServiceNode())
    """
    mapping = _COLUMN_TO_PROTO.get(type_name)
    if not mapping:
        return row
    return {mapping.get(k, k): v for k, v in row.items()}


def proto_to_ladybug(type_name: NodeType | RelType, obj: dict[str, object]) -> dict[str, object]:
    """Remap protobuf field names to LadybugDB column names.

    Use this when converting a protobuf message (or its dict representation)
    to a row suitable for writing to the database. Only fields with a
    ``(ladybug.column)`` override are remapped; all other keys pass through
    unchanged. Returns the input unchanged for types with no remapped columns.

    Example::

        obj = MessageToDict(msg, preserving_proto_field_name=True)
        row = proto_to_ladybug("Service", obj)
        # {"id": "s1", "name": "api", "repoUrl": "https://..."}
    """
    mapping = _PROTO_TO_COLUMN.get(type_name)
    if not mapping:
        return obj
    return {mapping.get(k, k): v for k, v in obj.items()}
