// Code generated by protoc-gen-ladybug. DO NOT EDIT.

package graph

import (
	"fmt"
	"strings"
)

// NodeSchemaStatements contains the DDL statements for all node tables.
var NodeSchemaStatements = []string{
	`CREATE NODE TABLE IF NOT EXISTS File(id STRING PRIMARY KEY, name STRING, path STRING, language STRING, lines INT32, checksum BLOB, labels STRING[])`,
	`CREATE NODE TABLE IF NOT EXISTS Function(id STRING, name STRING PRIMARY KEY, signature STRING, startLine INT32, endLine INT32, exported BOOL, complexity INT32)`,
	`CREATE NODE TABLE IF NOT EXISTS Class(id STRING PRIMARY KEY, name STRING, kind STRING, start_line INT32, end_line INT32, exported BOOL, implements STRING[])`,
	`CREATE NODE TABLE IF NOT EXISTS Package(id STRING, name STRING, version STRING, path STRING PRIMARY KEY)`,
	`CREATE NODE TABLE IF NOT EXISTS Service(id STRING PRIMARY KEY, name STRING, repoUrl STRING, port UINT32, owners STRING[])`,
}

// NodeType identifies a node table type.
type NodeType string

// NodeTypeFile is the node type name for File nodes.
const NodeTypeFile NodeType = "File"

// NodeTypeFunction is the node type name for Function nodes.
const NodeTypeFunction NodeType = "Function"

// NodeTypeClass is the node type name for Class nodes.
const NodeTypeClass NodeType = "Class"

// NodeTypePackage is the node type name for Package nodes.
const NodeTypePackage NodeType = "Package"

// NodeTypeService is the node type name for Service nodes.
const NodeTypeService NodeType = "Service"

// NodeTypes contains all node type names.
var NodeTypes = []NodeType{
	NodeTypeFile,
	NodeTypeFunction,
	NodeTypeClass,
	NodeTypePackage,
	NodeTypeService,
}

// ColumnDef describes a single column in a node table.
type ColumnDef struct {
	Name string
	Type string
}

// NodeColumns maps each node type to its ordered list of column definitions.
var NodeColumns = map[NodeType][]ColumnDef{
	NodeTypeFile: {
		{Name: "id", Type: "STRING"},
		{Name: "name", Type: "STRING"},
		{Name: "path", Type: "STRING"},
		{Name: "language", Type: "STRING"},
		{Name: "lines", Type: "INT32"},
		{Name: "checksum", Type: "BLOB"},
		{Name: "labels", Type: "STRING[]"},
	},
	NodeTypeFunction: {
		{Name: "id", Type: "STRING"},
		{Name: "name", Type: "STRING"},
		{Name: "signature", Type: "STRING"},
		{Name: "startLine", Type: "INT32"},
		{Name: "endLine", Type: "INT32"},
		{Name: "exported", Type: "BOOL"},
		{Name: "complexity", Type: "INT32"},
	},
	NodeTypeClass: {
		{Name: "id", Type: "STRING"},
		{Name: "name", Type: "STRING"},
		{Name: "kind", Type: "STRING"},
		{Name: "start_line", Type: "INT32"},
		{Name: "end_line", Type: "INT32"},
		{Name: "exported", Type: "BOOL"},
		{Name: "implements", Type: "STRING[]"},
	},
	NodeTypePackage: {
		{Name: "id", Type: "STRING"},
		{Name: "name", Type: "STRING"},
		{Name: "version", Type: "STRING"},
		{Name: "path", Type: "STRING"},
	},
	NodeTypeService: {
		{Name: "id", Type: "STRING"},
		{Name: "name", Type: "STRING"},
		{Name: "repoUrl", Type: "STRING"},
		{Name: "port", Type: "UINT32"},
		{Name: "owners", Type: "STRING[]"},
	},
}

// NodeColumnNames maps each node type to its ordered list of column names.
var NodeColumnNames = map[NodeType][]string{
	NodeTypeFile: {
		"id",
		"name",
		"path",
		"language",
		"lines",
		"checksum",
		"labels",
	},
	NodeTypeFunction: {
		"id",
		"name",
		"signature",
		"startLine",
		"endLine",
		"exported",
		"complexity",
	},
	NodeTypeClass: {
		"id",
		"name",
		"kind",
		"start_line",
		"end_line",
		"exported",
		"implements",
	},
	NodeTypePackage: {
		"id",
		"name",
		"version",
		"path",
	},
	NodeTypeService: {
		"id",
		"name",
		"repoUrl",
		"port",
		"owners",
	},
}

// RelPair identifies a (FROM, TO) node-type pair for a relationship table.
//
// Ladybug requires every pair a rel label spans to be declared in the
// initial CREATE REL TABLE statement; subsequent CREATE REL TABLE IF
// NOT EXISTS calls for the same label are silent no-ops. Pass every
// pair the label needs in a single RelSchema<Name> call.
type RelPair struct {
	From string
	To   string
}

// joinRelPairs renders a slice of RelPairs as a comma-separated list of
// "FROM X TO Y" clauses suitable for the body of a CREATE REL TABLE.
func joinRelPairs(pairs []RelPair) string {
	parts := make([]string, 0, len(pairs))
	for _, p := range pairs {
		parts = append(parts, fmt.Sprintf("FROM %s TO %s", p.From, p.To))
	}
	return strings.Join(parts, ", ")
}

// RelSchemaCalls returns the CREATE REL TABLE DDL for Calls relationships.
//
// Pass every (FROM, TO) pair the CALLS label needs in a single call; all
// pairs must be declared in the initial CREATE REL TABLE statement.
func RelSchemaCalls(pairs ...RelPair) string {
	return fmt.Sprintf(`CREATE REL TABLE IF NOT EXISTS CALLS(%s, id STRING, args STRING, confidence FLOAT)`, joinRelPairs(pairs))
}

// RelSchemaDefinedIn returns the CREATE REL TABLE DDL for DefinedIn relationships.
//
// Pass every (FROM, TO) pair the DEFINED_IN label needs in a single call; all
// pairs must be declared in the initial CREATE REL TABLE statement.
func RelSchemaDefinedIn(pairs ...RelPair) string {
	return fmt.Sprintf(`CREATE REL TABLE IF NOT EXISTS DEFINED_IN(%s, id STRING, startLine INT32, endLine INT32)`, joinRelPairs(pairs))
}

// RelSchemaDependsOn returns the CREATE REL TABLE DDL for DependsOn relationships.
//
// Pass every (FROM, TO) pair the DEPENDS_ON label needs in a single call; all
// pairs must be declared in the initial CREATE REL TABLE statement.
func RelSchemaDependsOn(pairs ...RelPair) string {
	return fmt.Sprintf(`CREATE REL TABLE IF NOT EXISTS DEPENDS_ON(%s, id STRING, version STRING, dev BOOL)`, joinRelPairs(pairs))
}

// RelType identifies a relationship table type.
type RelType string

// RelTypeCalls is the relationship type name for Calls relationships.
const RelTypeCalls RelType = "CALLS"

// RelTypeDefinedIn is the relationship type name for DefinedIn relationships.
const RelTypeDefinedIn RelType = "DEFINED_IN"

// RelTypeDependsOn is the relationship type name for DependsOn relationships.
const RelTypeDependsOn RelType = "DEPENDS_ON"

// RelTypes contains all relationship type names.
var RelTypes = []RelType{
	RelTypeCalls,
	RelTypeDefinedIn,
	RelTypeDependsOn,
}

// RelColumns maps each rel type to its ordered list of column definitions.
var RelColumns = map[RelType][]ColumnDef{
	RelTypeCalls: {
		{Name: "id", Type: "STRING"},
		{Name: "args", Type: "STRING"},
		{Name: "confidence", Type: "FLOAT"},
	},
	RelTypeDefinedIn: {
		{Name: "id", Type: "STRING"},
		{Name: "startLine", Type: "INT32"},
		{Name: "endLine", Type: "INT32"},
	},
	RelTypeDependsOn: {
		{Name: "id", Type: "STRING"},
		{Name: "version", Type: "STRING"},
		{Name: "dev", Type: "BOOL"},
	},
}

// RelColumnNames maps each rel type to its ordered list of column names.
var RelColumnNames = map[RelType][]string{
	RelTypeCalls: {
		"id",
		"args",
		"confidence",
	},
	RelTypeDefinedIn: {
		"id",
		"startLine",
		"endLine",
	},
	RelTypeDependsOn: {
		"id",
		"version",
		"dev",
	},
}

// columnToProto maps type name -> column name -> proto field name for renamed columns.
var columnToProto = map[string]map[string]string{
	string(NodeTypeFunction): {"startLine": "start_line", "endLine": "end_line"},
	string(NodeTypeService):  {"repoUrl": "repo_url"},
	string(RelTypeDefinedIn): {"startLine": "start_line", "endLine": "end_line"},
}

// protoToColumn maps type name -> proto field name -> column name for renamed columns.
var protoToColumn = map[string]map[string]string{
	string(NodeTypeFunction): {"start_line": "startLine", "end_line": "endLine"},
	string(NodeTypeService):  {"repo_url": "repoUrl"},
	string(RelTypeDefinedIn): {"start_line": "startLine", "end_line": "endLine"},
}

// LadybugToProto remaps LadybugDB column names to protobuf field names.
//
// Use this when reading a row from the database and converting it to a
// protobuf message. Only columns with a (ladybug.column) override are
// remapped; all other keys pass through unchanged. Returns the input
// unchanged for types with no remapped columns.
//
// Accepts NodeType, RelType, or any ~string type.
func LadybugToProto[T ~string](typeName T, row map[string]any) map[string]any {
	mapping := columnToProto[string(typeName)]
	if mapping == nil {
		return row
	}
	result := make(map[string]any, len(row))
	for k, v := range row {
		if mapped, ok := mapping[k]; ok {
			result[mapped] = v
		} else {
			result[k] = v
		}
	}
	return result
}

// ProtoToLadybug remaps protobuf field names to LadybugDB column names.
//
// Use this when converting a protobuf message (or its map representation)
// to a row suitable for writing to the database. Only fields with a
// (ladybug.column) override are remapped; all other keys pass through
// unchanged. Returns the input unchanged for types with no remapped columns.
//
// Accepts NodeType, RelType, or any ~string type.
func ProtoToLadybug[T ~string](typeName T, obj map[string]any) map[string]any {
	mapping := protoToColumn[string(typeName)]
	if mapping == nil {
		return obj
	}
	result := make(map[string]any, len(obj))
	for k, v := range obj {
		if mapped, ok := mapping[k]; ok {
			result[mapped] = v
		} else {
			result[k] = v
		}
	}
	return result
}
