// Auto-generated by protoc-gen-ladybug — do not edit.

export const NODE_SCHEMA_STATEMENTS = [
  `CREATE NODE TABLE IF NOT EXISTS Commit(sha STRING PRIMARY KEY, message STRING, timestamp INT64, authorEmail STRING)`,
  `CREATE NODE TABLE IF NOT EXISTS Author(email STRING PRIMARY KEY, name STRING)`,
] as const;

export const NODE_TYPES = [
  'Commit',
  'Author',
] as const;

export type NodeType = (typeof NODE_TYPES)[number];

export type ColumnType =
  | 'STRING' | 'INT32' | 'INT64' | 'UINT32' | 'UINT64'
  | 'FLOAT' | 'DOUBLE' | 'BOOL' | 'BLOB'
  | 'STRING[]' | 'INT32[]' | 'INT64[]' | 'UINT32[]' | 'UINT64[]'
  | 'FLOAT[]' | 'DOUBLE[]' | 'BOOL[]' | 'BLOB[]';

export interface ColumnDef {
  readonly name: string;
  readonly type: ColumnType;
}

export const NODE_COLUMNS: Readonly<Record<NodeType, readonly ColumnDef[]>> = {
  Commit: [
    { name: 'sha', type: 'STRING' },
    { name: 'message', type: 'STRING' },
    { name: 'timestamp', type: 'INT64' },
    { name: 'authorEmail', type: 'STRING' },
  ],
  Author: [
    { name: 'email', type: 'STRING' },
    { name: 'name', type: 'STRING' },
  ],
} as const;

export const NODE_COLUMN_NAMES: Readonly<Record<NodeType, readonly string[]>> = {
  Commit: [
    'sha',
    'message',
    'timestamp',
    'authorEmail',
  ],
  Author: [
    'email',
    'name',
  ],
} as const;

/**
 * A (FROM, TO) node-type pair for a relationship table.
 *
 * Ladybug requires every pair a rel label spans to be declared in the
 * initial CREATE REL TABLE statement; subsequent CREATE REL TABLE IF
 * NOT EXISTS calls for the same label are silent no-ops. Pass every
 * pair the label needs in a single REL_SCHEMA call.
 */
export interface RelPair {
  readonly from: string;
  readonly to: string;
}

function joinRelPairs(pairs: ReadonlyArray<RelPair>): string {
  return pairs.map(p => `FROM ${p.from} TO ${p.to}`).join(', ');
}

export const REL_SCHEMA = {
  AUTHORED: (pairs: ReadonlyArray<RelPair>) =>
    `CREATE REL TABLE IF NOT EXISTS AUTHORED(${joinRelPairs(pairs)}, id STRING)`,
  MODIFIES: (pairs: ReadonlyArray<RelPair>) =>
    `CREATE REL TABLE IF NOT EXISTS MODIFIES(${joinRelPairs(pairs)}, id STRING, additions INT32, deletions INT32)`,
} as const;

export const REL_TYPES = [
  'AUTHORED',
  'MODIFIES',
] as const;

export type RelType = (typeof REL_TYPES)[number];

export const REL_COLUMNS: Readonly<Record<RelType, readonly ColumnDef[]>> = {
  AUTHORED: [
    { name: 'id', type: 'STRING' },
  ],
  MODIFIES: [
    { name: 'id', type: 'STRING' },
    { name: 'additions', type: 'INT32' },
    { name: 'deletions', type: 'INT32' },
  ],
} as const;

export const REL_COLUMN_NAMES: Readonly<Record<RelType, readonly string[]>> = {
  AUTHORED: [
    'id',
  ],
  MODIFIES: [
    'id',
    'additions',
    'deletions',
  ],
} as const;

const COLUMN_TO_PROTO: Partial<Readonly<Record<NodeType | RelType, Readonly<Record<string, string>>>>> = {
  Commit: { 'authorEmail': 'author_email' },
} as const;

const PROTO_TO_COLUMN: Partial<Readonly<Record<NodeType | RelType, Readonly<Record<string, string>>>>> = {
  Commit: { 'author_email': 'authorEmail' },
} as const;

/**
 * Remap LadybugDB column names to protobuf field names.
 *
 * Use this when reading a row from the database and converting it to a
 * protobuf message. Only columns with a `(ladybug.column)` override are
 * remapped; all other keys pass through unchanged. Returns the input
 * unchanged for types with no remapped columns.
 *
 * @example
 * ```ts
 * const row = { id: 's1', name: 'api', repoUrl: 'https://...' };
 * const protoObj = ladybugToProto('Service', row);
 * // { id: 's1', name: 'api', repo_url: 'https://...' }
 * ```
 */
export function ladybugToProto(typeName: NodeType | RelType, row: Record<string, unknown>): Record<string, unknown> {
  const mapping = COLUMN_TO_PROTO[typeName];
  if (!mapping) return row;
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(row)) {
    result[mapping[key] ?? key] = value;
  }
  return result;
}

/**
 * Remap protobuf field names to LadybugDB column names.
 *
 * Use this when converting a protobuf message (or its dict representation)
 * to a row suitable for writing to the database. Only fields with a
 * `(ladybug.column)` override are remapped; all other keys pass through
 * unchanged. Returns the input unchanged for types with no remapped columns.
 *
 * @example
 * ```ts
 * const obj = { id: 's1', name: 'api', repo_url: 'https://...' };
 * const row = protoToLadybug('Service', obj);
 * // { id: 's1', name: 'api', repoUrl: 'https://...' }
 * ```
 */
export function protoToLadybug(typeName: NodeType | RelType, obj: Record<string, unknown>): Record<string, unknown> {
  const mapping = PROTO_TO_COLUMN[typeName];
  if (!mapping) return obj;
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    result[mapping[key] ?? key] = value;
  }
  return result;
}
