# Auto-generated by protoc-gen-ladybug — do not edit.

from typing import Final, Literal

NODE_SCHEMA_STATEMENTS: Final[list[str]] = [
    "CREATE NODE TABLE IF NOT EXISTS Commit(sha STRING PRIMARY KEY, message STRING, timestamp INT64, authorEmail STRING)",
    "CREATE NODE TABLE IF NOT EXISTS Author(email STRING PRIMARY KEY, name STRING)",
]

NODE_TYPE_COMMIT: Final[str] = "Commit"
NODE_TYPE_AUTHOR: Final[str] = "Author"

NodeType = Literal["Commit"] | Literal["Author"]

NODE_TYPES: Final[list[NodeType]] = [
    NODE_TYPE_COMMIT,
    NODE_TYPE_AUTHOR,
]

NODE_COLUMNS: Final[dict[NodeType, list[tuple[str, str]]]] = {
    "Commit": [
        ("sha", "STRING"),
        ("message", "STRING"),
        ("timestamp", "INT64"),
        ("authorEmail", "STRING"),
    ],
    "Author": [
        ("email", "STRING"),
        ("name", "STRING"),
    ],
}

NODE_COLUMN_NAMES: Final[dict[NodeType, list[str]]] = {
    "Commit": [
        "sha",
        "message",
        "timestamp",
        "authorEmail",
    ],
    "Author": [
        "email",
        "name",
    ],
}


def rel_schema_authored(from_node: str, to_node: str) -> str:
    """Return the CREATE REL TABLE DDL for Authored relationships."""
    return f"CREATE REL TABLE IF NOT EXISTS AUTHORED(FROM {from_node} TO {to_node}, id STRING)"


def rel_schema_modifies(from_node: str, to_node: str) -> str:
    """Return the CREATE REL TABLE DDL for Modifies relationships."""
    return f"CREATE REL TABLE IF NOT EXISTS MODIFIES(FROM {from_node} TO {to_node}, id STRING, additions INT32, deletions INT32)"


REL_TYPE_AUTHORED: Final[str] = "AUTHORED"
REL_TYPE_MODIFIES: Final[str] = "MODIFIES"

RelType = Literal["AUTHORED"] | Literal["MODIFIES"]

REL_TYPES: Final[list[RelType]] = [
    REL_TYPE_AUTHORED,
    REL_TYPE_MODIFIES,
]

REL_COLUMNS: Final[dict[RelType, list[tuple[str, str]]]] = {
    "AUTHORED": [
        ("id", "STRING"),
    ],
    "MODIFIES": [
        ("id", "STRING"),
        ("additions", "INT32"),
        ("deletions", "INT32"),
    ],
}

REL_COLUMN_NAMES: Final[dict[RelType, list[str]]] = {
    "AUTHORED": [
        "id",
    ],
    "MODIFIES": [
        "id",
        "additions",
        "deletions",
    ],
}


_COLUMN_TO_PROTO: Final[dict[NodeType | RelType, dict[str, str]]] = {
    "Commit": {"authorEmail": "author_email"},
}

_PROTO_TO_COLUMN: Final[dict[NodeType | RelType, dict[str, str]]] = {
    "Commit": {"author_email": "authorEmail"},
}


def ladybug_to_proto(type_name: NodeType | RelType, row: dict[str, object]) -> dict[str, object]:
    """Remap LadybugDB column names to protobuf field names.

    Use this when reading a row from the database and converting it to a
    protobuf message via ``ParseDict``. Only columns with a ``(ladybug.column)``
    override are remapped; all other keys pass through unchanged. Returns the
    input unchanged for types with no remapped columns.

    Example::

        row = {"id": "s1", "name": "api", "repoUrl": "https://..."}
        msg = ParseDict(ladybug_to_proto("Service", row), ServiceNode())
    """
    mapping = _COLUMN_TO_PROTO.get(type_name)
    if not mapping:
        return row
    return {mapping.get(k, k): v for k, v in row.items()}


def proto_to_ladybug(type_name: NodeType | RelType, obj: dict[str, object]) -> dict[str, object]:
    """Remap protobuf field names to LadybugDB column names.

    Use this when converting a protobuf message (or its dict representation)
    to a row suitable for writing to the database. Only fields with a
    ``(ladybug.column)`` override are remapped; all other keys pass through
    unchanged. Returns the input unchanged for types with no remapped columns.

    Example::

        obj = MessageToDict(msg, preserving_proto_field_name=True)
        row = proto_to_ladybug("Service", obj)
        # {"id": "s1", "name": "api", "repoUrl": "https://..."}
    """
    mapping = _PROTO_TO_COLUMN.get(type_name)
    if not mapping:
        return obj
    return {mapping.get(k, k): v for k, v in obj.items()}
