// Code generated by protoc-gen-ladybug. DO NOT EDIT.

package commits

import (
	"fmt"
	"strings"
)

// NodeSchemaStatements contains the DDL statements for all node tables.
var NodeSchemaStatements = []string{
	`CREATE NODE TABLE IF NOT EXISTS Commit(sha STRING PRIMARY KEY, message STRING, timestamp INT64, authorEmail STRING)`,
	`CREATE NODE TABLE IF NOT EXISTS Author(email STRING PRIMARY KEY, name STRING)`,
}

// NodeType identifies a node table type.
type NodeType string

// NodeTypeCommit is the node type name for Commit nodes.
const NodeTypeCommit NodeType = "Commit"

// NodeTypeAuthor is the node type name for Author nodes.
const NodeTypeAuthor NodeType = "Author"

// NodeTypes contains all node type names.
var NodeTypes = []NodeType{
	NodeTypeCommit,
	NodeTypeAuthor,
}

// ColumnDef describes a single column in a node table.
type ColumnDef struct {
	Name string
	Type string
}

// NodeColumns maps each node type to its ordered list of column definitions.
var NodeColumns = map[NodeType][]ColumnDef{
	NodeTypeCommit: {
		{Name: "sha", Type: "STRING"},
		{Name: "message", Type: "STRING"},
		{Name: "timestamp", Type: "INT64"},
		{Name: "authorEmail", Type: "STRING"},
	},
	NodeTypeAuthor: {
		{Name: "email", Type: "STRING"},
		{Name: "name", Type: "STRING"},
	},
}

// NodeColumnNames maps each node type to its ordered list of column names.
var NodeColumnNames = map[NodeType][]string{
	NodeTypeCommit: {
		"sha",
		"message",
		"timestamp",
		"authorEmail",
	},
	NodeTypeAuthor: {
		"email",
		"name",
	},
}

// RelPair identifies a (FROM, TO) node-type pair for a relationship table.
//
// Ladybug requires every pair a rel label spans to be declared in the
// initial CREATE REL TABLE statement; subsequent CREATE REL TABLE IF
// NOT EXISTS calls for the same label are silent no-ops. Pass every
// pair the label needs in a single RelSchema<Name> call.
type RelPair struct {
	From string
	To   string
}

// joinRelPairs renders a slice of RelPairs as a comma-separated list of
// "FROM X TO Y" clauses suitable for the body of a CREATE REL TABLE.
func joinRelPairs(pairs []RelPair) string {
	parts := make([]string, 0, len(pairs))
	for _, p := range pairs {
		parts = append(parts, fmt.Sprintf("FROM %s TO %s", p.From, p.To))
	}
	return strings.Join(parts, ", ")
}

// RelSchemaAuthored returns the CREATE REL TABLE DDL for Authored relationships.
//
// Pass every (FROM, TO) pair the AUTHORED label needs in a single call; all
// pairs must be declared in the initial CREATE REL TABLE statement.
func RelSchemaAuthored(pairs ...RelPair) string {
	return fmt.Sprintf(`CREATE REL TABLE IF NOT EXISTS AUTHORED(%s, id STRING)`, joinRelPairs(pairs))
}

// RelSchemaModifies returns the CREATE REL TABLE DDL for Modifies relationships.
//
// Pass every (FROM, TO) pair the MODIFIES label needs in a single call; all
// pairs must be declared in the initial CREATE REL TABLE statement.
func RelSchemaModifies(pairs ...RelPair) string {
	return fmt.Sprintf(`CREATE REL TABLE IF NOT EXISTS MODIFIES(%s, id STRING, additions INT32, deletions INT32)`, joinRelPairs(pairs))
}

// RelType identifies a relationship table type.
type RelType string

// RelTypeAuthored is the relationship type name for Authored relationships.
const RelTypeAuthored RelType = "AUTHORED"

// RelTypeModifies is the relationship type name for Modifies relationships.
const RelTypeModifies RelType = "MODIFIES"

// RelTypes contains all relationship type names.
var RelTypes = []RelType{
	RelTypeAuthored,
	RelTypeModifies,
}

// RelColumns maps each rel type to its ordered list of column definitions.
var RelColumns = map[RelType][]ColumnDef{
	RelTypeAuthored: {
		{Name: "id", Type: "STRING"},
	},
	RelTypeModifies: {
		{Name: "id", Type: "STRING"},
		{Name: "additions", Type: "INT32"},
		{Name: "deletions", Type: "INT32"},
	},
}

// RelColumnNames maps each rel type to its ordered list of column names.
var RelColumnNames = map[RelType][]string{
	RelTypeAuthored: {
		"id",
	},
	RelTypeModifies: {
		"id",
		"additions",
		"deletions",
	},
}

// columnToProto maps type name -> column name -> proto field name for renamed columns.
var columnToProto = map[string]map[string]string{
	string(NodeTypeCommit): {"authorEmail": "author_email"},
}

// protoToColumn maps type name -> proto field name -> column name for renamed columns.
var protoToColumn = map[string]map[string]string{
	string(NodeTypeCommit): {"author_email": "authorEmail"},
}

// LadybugToProto remaps LadybugDB column names to protobuf field names.
//
// Use this when reading a row from the database and converting it to a
// protobuf message. Only columns with a (ladybug.column) override are
// remapped; all other keys pass through unchanged. Returns the input
// unchanged for types with no remapped columns.
//
// Accepts NodeType, RelType, or any ~string type.
func LadybugToProto[T ~string](typeName T, row map[string]any) map[string]any {
	mapping := columnToProto[string(typeName)]
	if mapping == nil {
		return row
	}
	result := make(map[string]any, len(row))
	for k, v := range row {
		if mapped, ok := mapping[k]; ok {
			result[mapped] = v
		} else {
			result[k] = v
		}
	}
	return result
}

// ProtoToLadybug remaps protobuf field names to LadybugDB column names.
//
// Use this when converting a protobuf message (or its map representation)
// to a row suitable for writing to the database. Only fields with a
// (ladybug.column) override are remapped; all other keys pass through
// unchanged. Returns the input unchanged for types with no remapped columns.
//
// Accepts NodeType, RelType, or any ~string type.
func ProtoToLadybug[T ~string](typeName T, obj map[string]any) map[string]any {
	mapping := protoToColumn[string(typeName)]
	if mapping == nil {
		return obj
	}
	result := make(map[string]any, len(obj))
	for k, v := range obj {
		if mapped, ok := mapping[k]; ok {
			result[mapped] = v
		} else {
			result[k] = v
		}
	}
	return result
}
