// Copyright 2026 OpenTrace Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Custom field options for protoc-gen-ladybug.
//
// Import this file in your .proto definitions to customize the generated
// LadybugDB schema:
//
//   import "ladybug/options.proto";
//
//   message FileNode {
//     string id         = 1 [(ladybug.primary_key) = true];
//     string file_path  = 2 [(ladybug.column) = "filePath"];
//   }

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ladybug/options.proto

package ladybug

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_ladybug_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51001,
		Name:          "ladybug.column",
		Tag:           "bytes,51001,opt,name=column",
		Filename:      "ladybug/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         51002,
		Name:          "ladybug.primary_key",
		Tag:           "varint,51002,opt,name=primary_key",
		Filename:      "ladybug/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// column overrides the DDL column name for this field.
	// If unset, the proto field name is used as-is.
	//
	// optional string column = 51001;
	E_Column = &file_ladybug_options_proto_extTypes[0]
	// primary_key marks this field as the primary key for a Node table.
	// If no field is marked, the first field is used by default.
	// Only one field per message should be marked as the primary key.
	//
	// optional bool primary_key = 51002;
	E_PrimaryKey = &file_ladybug_options_proto_extTypes[1]
)

var File_ladybug_options_proto protoreflect.FileDescriptor

const file_ladybug_options_proto_rawDesc = "" +
	"\n" +
	"\x15ladybug/options.proto\x12\aladybug\x1a google/protobuf/descriptor.proto::\n" +
	"\x06column\x12\x1d.google.protobuf.FieldOptions\x18\xb9\x8e\x03 \x01(\tR\x06column\x88\x01\x01:C\n" +
	"\vprimary_key\x12\x1d.google.protobuf.FieldOptions\x18\xba\x8e\x03 \x01(\bR\n" +
	"primaryKey\x88\x01\x01B0Z.github.com/kranklab/protoc-gen-ladybug/ladybugb\x06proto3"

var file_ladybug_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_ladybug_options_proto_depIdxs = []int32{
	0, // 0: ladybug.column:extendee -> google.protobuf.FieldOptions
	0, // 1: ladybug.primary_key:extendee -> google.protobuf.FieldOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ladybug_options_proto_init() }
func file_ladybug_options_proto_init() {
	if File_ladybug_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ladybug_options_proto_rawDesc), len(file_ladybug_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_ladybug_options_proto_goTypes,
		DependencyIndexes: file_ladybug_options_proto_depIdxs,
		ExtensionInfos:    file_ladybug_options_proto_extTypes,
	}.Build()
	File_ladybug_options_proto = out.File
	file_ladybug_options_proto_goTypes = nil
	file_ladybug_options_proto_depIdxs = nil
}
